### ISSUE TITLE
Comments are way to indistinguishable from the background

### ISSUE THREAD

**Issue by CoolTomatos** [dracula/jetbrains#1]
Colour of comments are way to0 similar to the editor background colour and not easy to read.
![image](https://user-images.githubusercontent.com/24667806/59157635-30d94a00-8aae-11e9-8fba-6fb789902c96.png)

**Comment by WhiteVermouth** [comment]
This color is specified in the official specification, you may found it in this [repo](https://github.com/dracula/dracula-theme). For now, you can modify it in **Preferences -> Editor -> Color Schema**. Next version, I'll try another color to make comments easier to read.

**Comment by CoolTomatos** [comment]
> Next version, I'll try another color to make comments easier to read.

谢谢老哥
