### ISSUE TITLE
Coloring glitch

### ISSUE THREAD

**Issue by mozesa** [dracula/jetbrains#11]
Dear **Developer**,

first off all I would like to express my satisfaction. This theme is a masterpiece. 👍 

Now I have updated my `PyCharm` to `2019.3` (_Windows 10_) the coloring behaves odd.
Just after installing the theme, it is coloured perfectly but whenever I _restart_ the `PyCharm` I get ugly brownish colour.

I enclosed the image.

![theme](https://user-images.githubusercontent.com/49973426/70226799-c39f2c80-1751-11ea-962d-896c7c679188.png)

Currently the workaround is to disable and enable again the `DraculaTheme`, which solves the problem. 🤓 

Thanks for your help in advance.

**Comment by WhiteVermouth** [comment]
- Release v1.5.0 has been submitted. Once approved, upgrade it.
- But It seems a bug in PyCharm 2019.3, some investigations are still necessary.

**Comment by WhiteVermouth** [comment]
Is this issue solved in v1.5.1 @mozesa

**Comment by mozesa** [comment]
@**WhiteVermouth**,

Yes, it is. :smile: 

Thanks! :+1:
