### ISSUE TITLE
从1.4.9升到1.5.0之后，在Editor->Color Scheme下面没有Dracula了

### ISSUE THREAD

**Issue by CoolTomatos** [dracula/jetbrains#12]
AppCode和Intellij IDEA里面，Dracula插件升级之后，Color Scheme里面Dracula消失了，编辑器配色回到了默认的Darcula。
但是UI部分还是Dracula。
就很奇怪。

**Comment by WhiteVermouth** [comment]
无法重现，尝试一下重装插件。
