### ISSUE TITLE
Low contrast hover in dropdown menus

### ISSUE THREAD

**Issue by Batalex** [dracula/jetbrains#15]
Hi,

Here is a dropdown menu on latest version (1.5.2).

![image](https://user-images.githubusercontent.com/11004857/70979650-4315ef80-20b2-11ea-874c-f2d080935d4e.png)

**Comment by WhiteVermouth** [comment]
Which OS? Can't reproduce on macOS.

**Comment by Batalex** [comment]
I am on Windows 10 1909.
It is odd though that dropdowns outside settings modal do not have this issue.
![image](https://user-images.githubusercontent.com/11004857/70997850-35726100-20d6-11ea-8e03-a92facefb6e3.png)

BTW, thank you for your work on this plugin. Such a pleasant and yet productive theme :)
