### ISSUE TITLE
Compatibility with PHPStorm 2020.1 EAP

### ISSUE THREAD

**Issue by ravanscafi** [dracula/jetbrains#17]
Hey guys!

There is a new PHPStorm EAP version (and certainly other IDE's too), and the latest dracula version doesn't work anymore with it. Can you please check? :wink: 

![image](https://user-images.githubusercontent.com/6104262/73557256-a88a2980-442f-11ea-9f5d-817528fcd703.png)

![image](https://user-images.githubusercontent.com/6104262/73557317-bcce2680-442f-11ea-8d02-1c1c03dfad2a.png)

Thanks and keep up with the good work!

**Comment by WhiteVermouth** [comment]
Fixed in v1.6.0, just wait for the approval of JetBrains.
