### ISSUE TITLE
Java code highlighted with white background, impossible to read.

### ISSUE THREAD

**Issue by sshahar1** [dracula/jetbrains#18]
Dracula theme version 1.6.2
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020

A line in the Java code is highlighted with very bright background making it impossible to read.
![image](https://user-images.githubusercontent.com/17417203/76160231-fed64080-6130-11ea-8064-721f6584fefe.png)

The code can be opened as it is the github repository: https://github.com/debezium/debezium and the class is **io.debezium.connector.postgresql.connection.AbstractMessageDecoder**

**Comment by WhiteVermouth** [comment]
It seems that you are not using Dracula color scheme. Open Preferences -> Editor -> Color Scheme, choose Dracula.

**Comment by sshahar1** [comment]
Hi, sorry for the confusion but the problem seems to vanish. My appologies
