### ISSUE TITLE
Support PHPStorm 2020.2 EAP

### ISSUE THREAD

**Issue by lukasluecke** [dracula/jetbrains#20]
Just like #17.

It might just need a quick update of the compatible version string, but I'm not sure. There are some new/updated layouts and widgets - see https://blog.jetbrains.com/phpstorm/2020/05/phpstorm-2020-2-early-access-program-is-now-open)

Thanks a lot in advance, can't imagine working without this theme anymore (and was very confused after the update, seeing the "default" theme for the first time in years 😬)

**Comment by WhiteVermouth** [comment]
Fixed temporary, upgrade to v1.7.0

**Comment by lukasluecke** [comment]
@WhiteVermouth Thank you! 🙂
