### ISSUE TITLE
Implement the official color scheme

### ISSUE THREAD

**Issue by mgartner** [dracula/jetbrains#21]
Looks like a few colors deviate from the official Dracula colorscheme. For example, the comments are brighter and the green color is brighter as well.

The official colors can be found here: https://draculatheme.com/contribute#color-palette

I might try to take a stab at this and put up a PR.

**Comment by WhiteVermouth** [comment]
The comment color is an exception, the original official comment color may cause the comment hard to read, issue #1 and issue https://github.com/dracula/dracula-theme/issues/318 mentioned this. So it is adjusted more brighter.
The green color is actually the same.

**Comment by mgartner** [comment]
Ahh I see. Thanks. Changing my anti-aliasing settings to “greyscale” seems to have helped tone down the green.
