### ISSUE TITLE
Wrong colors in AppCode for Swift/ObjC

### ISSUE THREAD

**Issue by jandamm** [dracula/jetbrains#22]
<img width="1109" alt="Screenshot" src="https://user-images.githubusercontent.com/5963139/90062426-f689bf00-dce7-11ea-841f-f4e5f09b2af0.png">

I would expect different colors for `types` and `functions`.

**Comment by WhiteVermouth** [comment]
Currently Swift and OC doesn't support well, and will optimize soon.

**Comment by WhiteVermouth** [comment]
Please check out v1.7.1

**Comment by jandamm** [comment]
Looks awesome now 👍 Thanks 🙏
