### ISSUE TITLE
The colors are messed up after the update to 1.7.1

### ISSUE THREAD

**Issue by uglypixels** [dracula/jetbrains#24]
The syntax coloring used to look like this here:
![image](https://user-images.githubusercontent.com/10457166/91295690-bfadb180-e79b-11ea-8be5-4aa87d70f811.png)

After the update first the editor turned all white. After restarting Rider the colors now look like this:
![image](https://user-images.githubusercontent.com/10457166/91295823-f257aa00-e79b-11ea-9d43-3e7ebd256965.png)

**Comment by uglypixels** [comment]
FYI I have updated this plugin to 1.7.2 and the color scheme is still messed up for C#. I have installed this theme on a second computer and the problem is the same.

**Comment by WhiteVermouth** [comment]
@uglypixels Provide a screenshot of v1.7.2

**Comment by uglypixels** [comment]
1.7.2
![image](https://user-images.githubusercontent.com/10457166/91721924-d4be8200-eb99-11ea-9654-04779a55c175.png)

Also I tried going back to 1.7.0 but it looks the same for me. I cannot go further because older versions are incompatible with Rider 2020.2.1

**Comment by WhiteVermouth** [comment]
Where does the screenshot you mentioned in original issue come from? All dracula themes use the same color palette, but due to platform differences, color scheme may be different. #ffb86c is used to color instance field and property in C#.
The color palette: https://github.com/dracula/dracula-theme#color-palette

**Comment by uglypixels** [comment]
The original img is from google images because I couldn't find screenshots. The theme looks much better for 1.7.2 and the color values are ok but some elements are still mistaken. Here is an old screenshot I took, brackets used to be light:
![image](https://user-images.githubusercontent.com/10457166/91723435-09333d80-eb9c-11ea-955d-d32704fbf822.png)
![image](https://user-images.githubusercontent.com/10457166/91723686-721ab580-eb9c-11ea-94cf-31644cf91d7e.png)
Now they are purple:
![image](https://user-images.githubusercontent.com/10457166/91725052-75af3c00-eb9e-11ea-8e7a-35f6f42081be.png)
Green:
![image](https://user-images.githubusercontent.com/10457166/91725069-7e077700-eb9e-11ea-811c-602f172e7e35.png)
Or Yellow:
![image](https://user-images.githubusercontent.com/10457166/91725082-8495ee80-eb9e-11ea-8a8a-ef88d65fa397.png)

The properties looked like this:
![image](https://user-images.githubusercontent.com/10457166/91724704-fde11180-eb9d-11ea-9baf-99543a99637f.png)
Now they look like this:
![image](https://user-images.githubusercontent.com/10457166/91724735-0a656a00-eb9e-11ea-81eb-f9246376adf5.png)

Also I think the UI of Rider looks pale now:
![image](https://user-images.githubusercontent.com/10457166/91724200-3d5b2e00-eb9d-11ea-8b49-337ba75afa92.png)

**Comment by WhiteVermouth** [comment]
1. The brackets color has no specification, and it is made colorful deliberately. Cause I think it's more beautiful...
2. The property and field color will be modified in v1.7.3 according to [specification](https://spec.draculatheme.com/#sec-Variables)
3. Any advice on polishing the UI details?

**Comment by uglypixels** [comment]
1. 2. I just don't find it ok to change something that lasted for so long that people got used to it. I'll just keep that customized on my end to fit my own preference.
3. I don't have the old ref, it used to look good, darker, more readable. Maybe it's a matter of new Rider versions, I don't know for sure.

**Comment by WhiteVermouth** [comment]
OK. I'll revert the bracket color.

**Comment by WhiteVermouth** [comment]
v1.8.0 totally conform to the official specification, but official specification lacks some colors like bracket color and instance field, other Dracula themes keep theme pure white(or uncolored), while before v1.8.0 JetBrains Dracula use some custom colors, such as bracket color, field color and local variable color. After v1.8.0 released, some users reflect that they prefer the original color scheme, colorful brackets for example. So in v1.8.1, I'll still conform to the specification, but apart from that, I'll reserve the custom colors, mostly the same to v1.7.2

**Comment by WhiteVermouth** [comment]
I found another way to solve this problem. There will be two color schemes named **Dracula** and **Dracula Colorful**, the colorful one will contain these custom colors like colorful brackets, and the default one will keep simple and standard.
