### ISSUE TITLE
1.8.0 makes code less readable 

### ISSUE THREAD

**Issue by CoolTomatos** [dracula/jetbrains#25]
## Screenshot of 1.7.2
![image](https://user-images.githubusercontent.com/24667806/91837057-eeb89d00-ec4b-11ea-9b13-0e7320f24a07.png)

## Screenshot of 1.8.0
![image](https://user-images.githubusercontent.com/24667806/91836952-c92b9380-ec4b-11ea-8f2d-3fd96bb99495.png)

##
1. Local variables (used to be grayish) are no longer differentiate from class fields (used to be orange).
Now they are both white and the white is a bit too bright and jarring in my opinion.
2. brackets are no longer colored.

**Comment by WhiteVermouth** [comment]
According to [Dracula Specification](https://spec.draculatheme.com/), bracket color is not specified, local variable color is pure white (#f8f8f2). But previously I colored theme with colors outside the Dracula palette, as you see, the colored brackets and gray variable etc. In v1.8.1, I'll consider revert these colors.

**Comment by CoolTomatos** [comment]
Personally speaking, your alternative colour scheme used previously was way better than the "Official" specified colour scheme.

For example with `this.numberOne = numberOne;` I would be more interested in the field variable `this.numberOne` compared with the parameter `numberOne`. Especially considering that in functional programming parameter values should mostly stay untouched. Therefore I think highlighting the former with orange and the latter with grey makes more sense.

**Comment by WhiteVermouth** [comment]
I'll release two color schemes, named **Dracula** and **Dracula Colorful**. Users just choose the one they prefer.
