### ISSUE TITLE
CMake highlight for CLion

### ISSUE THREAD

**Issue by horusxnetworks** [dracula/jetbrains#26]
Hi,
I'm using Dracula theme for CLion and I found difficulties on writing code because CMake highlight is not good enough.
In my opinion, gedit has the best syntax highlight for CMake. Please check screenshots below:
gedit
![Screenshot from 2020-09-18 09-22-53](https://user-images.githubusercontent.com/66507196/93548193-eb821880-f990-11ea-9070-ca6e5dc8cc81.png)
vs CLion with Dracula
![Screenshot from 2020-09-18 09-23-26](https://user-images.githubusercontent.com/66507196/93548237-09e81400-f991-11ea-87b0-80b6a800dee7.png)

The improvements from gedit over Dracula come from it's hightlight syntax, color matching.
Could we consider to add this feature?

**Comment by WhiteVermouth** [comment]
I can't find the color scheme for **CMakeLists.txt** file in **Preferences -> Editor -> Color scheme**. So further investigation needed.

**Comment by WhiteVermouth** [comment]
Hi @triangulumlabs
CLion currently has no official entry to change the CMake syntax color. However, you have a workaround, you can install [CMake Simple Highlighter](https://plugins.jetbrains.com/plugin/10089-cmake-simple-highlighter) extension. This plugin enhances the CMake syntax highlight, also you can customize the color in **Preferences -> Editor -> Color scheme -> CMake additional syntax**. Cause this is not an official feature, **Dracula Theme** may not support this 3rd-party plugin enhanced syntax highlight, you may do it yourself.
