### ISSUE TITLE
Theme not Available in Rider Marketplace

### ISSUE THREAD

**Issue by rena0157** [dracula/jetbrains#27]
I tried to install the theme following the instruction on https://draculatheme.com/jetbrains but it looks like the theme is not available within the Rider Marketplace.

![image](https://user-images.githubusercontent.com/33334607/95097500-8d2c9800-06fb-11eb-806c-3ccc9e500e33.png)

Am I missing anything here? I have no custom repositories and this is a pretty fresh install of Rider 2020.3 EAP2.

**Comment by WhiteVermouth** [comment]
It's a 2020.3 compatibility issue. I've fixed it in v1.8.3. Please try again.

**Comment by rena0157** [comment]
Fixed Thanks!
