### ISSUE TITLE
Magic Constants (PHP)

### ISSUE THREAD

**Issue by GitHub-Mike** [dracula/jetbrains#28]
I'm using PhpStorm 2020.2 and can't find a way to format magic constants differently than "simple" constants.

Is this a PhpStorm problem or a missing theme feature?

**Comment by WhiteVermouth** [comment]
Could you provide a piece of sample codes and some screenshots?

**Comment by GitHub-Mike** [comment]
I can make a screenshot if you could tell me under which sub-item of the Color Scheme the "magic constants" setting should be located.

**Comment by WhiteVermouth** [comment]
Go to Preferences -> Editor -> Color Scheme -> PHP, all PHP color schemes locate at there. And I'm not familiar with PHP language.

**Comment by GitHub-Mike** [comment]
Here is a screenshot with Settings -> Editor -> Color Scheme -> PHP.

Missing a way to format magic constants differently than "simple" constants.

![PhpStorm-2020 2 2-color-scheme](https://user-images.githubusercontent.com/18616892/96269412-a0c4e200-0fca-11eb-9b53-18c09630369a.jpg)

**Comment by WhiteVermouth** [comment]
I found that the IDE only offers one `Constant` property and no more relative properties like `Magic Constant`, which means all constants keep the same color. So I guess PhpStorm doesn't offer this syntax highlight feature.

**Comment by GitHub-Mike** [comment]
OK, thanks for your research! Then I close the issue now.
