### ISSUE TITLE
Color scheme lost after update

### ISSUE THREAD

**Issue by browniebroke** [dracula/jetbrains#29]
I'm not sure if it's a problem with the theme, my IDE (PyCharm) or if it's specific to my setup, but each time I'm updating the theme, I get the "Editor > Color Scheme" setting lost and reset to the default one. What's more, the "Dracula" and "Dracula Colorful" schemes are not listed in the drop down, and I need to restart the IDE for them to be picked up.

The IDE theme is fine, the menu are purple when selected. The color scheme is used for styling the code itself. 

Is anyone else having this issue or is it just me?

## Expected:

![image](https://user-images.githubusercontent.com/861044/99510937-8b532700-297f-11eb-92c4-0df6a203ff88.png)

## With the bug 

Unfortunately I just fixed it now, so I don't have a screenshot of the bug, but I'll add it next time it happens.

**Comment by WhiteVermouth** [comment]
The  JetBrains IDEs' **Dynamic Plugin** feature(users no need to restart IDE after updating plugins) currently is not quite stable and reliable. So, to avoid some strange bugs, I recommend restart IDE everytime after updating the plugin.

**Comment by browniebroke** [comment]
Ok fair enough. So looking at [the documentation](https://jetbrains.org/intellij/sdk/docs/basics/plugin_structure/dynamic_plugins.html) on this, this is something declared by this project, right?

> If a plugin *requires* restart (e.g., due to using native libraries) specify `require-restart="true"` for `<idea-plugin>` root tag in `plugin.xml`

FWIW, I wouldn't mind delaying the theme update until I restart the editor myself (which I do every day). The main project I develop is using Docker and an IDE restart is expensive as it causes a general refresh of remote skeletons which takes a few minutes.

I appreciate that other users might have different usages than me though, and this is not a major nuisance either for me.

**Comment by WhiteVermouth** [comment]
Restart is an advice, only when color schemes lost. I'd rather not enforce restart with hard coded configuration.

**Comment by browniebroke** [comment]
The issue was gone in the most recent update. Color theme was briefly lost but then recovered by itself.
