### ISSUE TITLE
请问为什么每次更新code配色都会变呢？

### ISSUE THREAD

**Issue by linglingqi007** [dracula/jetbrains#3]
因为我用了idea装了go的插件。每次更新theme配置都变了呢？感觉这个idea里面不是很兼容别的语言么？如果直接用goland安装这个theme的话。就没有这个问题呢。
现在的插件版本是1.4.0呢，兼容2019.2版本的ide。但是这个配色反差很大呢。是我使用的姿势不对么？
![image](https://user-images.githubusercontent.com/6560524/61924844-27436d00-af9c-11e9-9851-2da776df1edc.png)
![image](https://user-images.githubusercontent.com/6560524/61924851-2d394e00-af9c-11e9-9d4c-d025cbd3e12e.png)

**Comment by WhiteVermouth** [comment]
当前版本未针对Go语言的配色进行优化，下一版本会修复这个问题。

**Comment by WhiteVermouth** [comment]
#4 新版本 1.4.1 已提交审核，加入了Go语言的支持。

**Comment by linglingqi007** [comment]
好的。真棒。谢谢
