### ISSUE TITLE
Dracula Pro not working for IntelliJ 2020.3

### ISSUE THREAD

**Issue by barriem** [dracula/jetbrains#32]
![Screenshot 2020-12-03 at 11 25 41](https://user-images.githubusercontent.com/526154/101010784-4ec82380-355a-11eb-9053-635e926102b3.png)

the UI reverts to Dracula (non-pro) which is not as nice IMO

**Comment by WhiteVermouth** [comment]
Sorry for the inconvenience, JetBrains 2020.3 is a new release, please wait for a moment.
Dracula PRO needs a upgrade for JetBrains 2020.3 @zenorocha

**Comment by zenorocha** [comment]
@barriem @WhiteVermouth this has been updated 2 months ago and communicated via email. You can download the latest version on gumroad.com

> Closing since this repository is only for the Dracula Open Source version, not Dracula PRO

**Comment by barriem** [comment]
ah awesome, sorry I missed that.  Thanks @zenorocha @WhiteVermouth

**Comment by barriem** [comment]
Hi @zenorocha, 

I just download the zipfile from gumroad, via the link in the e-mail from Halloween - but I get the same error in IntelliJ :(

**Comment by barriem** [comment]
guys, I'm so dumb :D sorry about this - I had the folder already in my downloads from when I installed 1.2.0..  and that's the one I re-added again.   with the updated 1.3.0 it works perfectly.

sorry 👍
