### ISSUE TITLE
Scrollbar - Highlight color used for FIXMEs is confusing with ERRORs' color

### ISSUE THREAD

**Issue by mothinx** [dracula/jetbrains#33]
Hello there.
First of all, thank you for the FIXME highlight feature using this beautifull purple 🤟 .

I would like to share something i have trouble with:
The red shade used for highlighting FIXMEs in the [scrollbar ](https://www.jetbrains.com/help/idea/2020.3/using-code-editor.html#scrollbar) is too confusing for me with the red ones used for highlighting ERRORs even if i don't have color blindness issues.

Here is an exemple
![image](https://user-images.githubusercontent.com/9392139/102472484-9cfb1d80-4056-11eb-8621-6a456398572f.png)

And a zoom:
![image](https://user-images.githubusercontent.com/9392139/102472314-7a690480-4056-11eb-85fc-4aabd382b36a.png)

I can see two problems here:

- ERRORs are not enought highlighted vs FIXME (in my point of view, erros are top one priority and i want my eyes to catch it as lightning speed)
- The darker red used do not "pop" enought, even with good eyes and good screen.

What about using the same purple for FIXMES in the scrollbar ?

**Comment by WhiteVermouth** [comment]
Thank you for your advice. I will enhance the scrollbar symbol colors soon.

**Comment by WhiteVermouth** [comment]
v1.9.5 is now released. Check it out.

**Comment by mothinx** [comment]
![image](https://user-images.githubusercontent.com/9392139/102752024-33865200-4369-11eb-90e8-8b8872b9b511.png)
That's perfect. Thank you so much for your work.
