### ISSUE TITLE
dracula pro 2020.3 color bugged

### ISSUE THREAD

**Issue by nico281** [dracula/jetbrains#34]
Hi, How are you?
Dracula pro on WebStorm 2020.3 is bugged. the font color on all menus are black. I just followed the readme and install the plugin.
cheers
![image](https://user-images.githubusercontent.com/15875218/103185152-e25eec80-4899-11eb-8d33-60b368112acc.png)

**Comment by WhiteVermouth** [comment]
You installed **Material Theme UI**, this theme may conflict with other themes like **Dracula Theme**. Disable or uninstall **Material Theme UI**, then restart IDE.

**Comment by nico281** [comment]
that was the issue. thanks a lot @WhiteVermouth
