### ISSUE TITLE
Too dark separator in context menu

### ISSUE THREAD

**Issue by slaviczavik** [dracula/jetbrains#35]
After update to latest version (1.10.1) there is a disturbing separator in context menu. Is this intended or it is an issue?

![Screenshot 2021-01-14 at 17 07 11](https://user-images.githubusercontent.com/6020945/104617580-e3f72580-568b-11eb-91cf-aaf26c1bea83.png)

**Comment by WhiteVermouth** [comment]
Another lighter color for separator is picked in v1.10.2. Check it out.
