### ISSUE TITLE
Database tool window with predefined colors is unreadable

### ISSUE THREAD

**Issue by MatyCZ** [dracula/jetbrains#36]
Database tool window with selected color is unreadable, predefined colors are too bright. There is no problem in Dracula PRO.

![database_tool_window](https://user-images.githubusercontent.com/318575/104693731-73431e00-570a-11eb-8275-e5a800120c84.jpg)

---

You can enable Database tool window in DataGrip, PHPStorm, IntelliJ IDEA Ultimate: `View | Tool Windows | Database` and you can set color of data source in context menu: `Color Settings...` or `Properties...`

**Data color settings**
![data_color_settings](https://user-images.githubusercontent.com/318575/104692752-c7e59980-5708-11eb-905c-1d64fb751c48.jpg)

**Data source and drivers**
![data_sources_and_drivers](https://user-images.githubusercontent.com/318575/104693749-79d19580-570a-11eb-9a54-3a8dd846a51c.jpg)

**Comment by WhiteVermouth** [comment]
Fixed v1.10.3
