### ISSUE TITLE
DocBlock is almost invisible in selection

### ISSUE THREAD

**Issue by MatyCZ** [dracula/jetbrains#37]
When you select some code with docblock (PHP in this case), docblock is almost invisible.

![docblock_almostNotVisible](https://user-images.githubusercontent.com/318575/104694983-4e4faa80-570c-11eb-98a3-60e174b357a3.jpg)

**Comment by WhiteVermouth** [comment]
For this issue, switch to `Dracula Colorful` as a workaround. Will fix in next release.

**Comment by WhiteVermouth** [comment]
Fixed in v1.10.3
