### ISSUE TITLE
Code completion window has default background color

### ISSUE THREAD

**Issue by MatyCZ** [dracula/jetbrains#38]
Code completion has default color - no color from Dracula color pallete.

![codeCompletion_backgroundColor](https://user-images.githubusercontent.com/318575/104695591-4cd2b200-570d-11eb-9a8e-0c4dbc2427a5.jpg)

**Comment by WhiteVermouth** [comment]
Fixed v1.10.3

**Comment by MatyCZ** [comment]
After upgrading to version 2021.2 code completion window has default background color again:

![codeCompletionWindow](https://user-images.githubusercontent.com/318575/130771277-dfda7686-da85-4d62-b36c-342781e89fff.png)

**Comment by WhiteVermouth** [comment]
Fixed again in v1.12.1
