### ISSUE TITLE
[Feature Request] Italics for items in parentheses like vscode theme

### ISSUE THREAD

**Issue by moishinetzer** [dracula/jetbrains#39]
Is it possible to implement the same styling (such as italics on the relevant code blocks)  the same way that dracula formats their code in vscode?

**Comment by WhiteVermouth** [comment]
Upgrade to v1.10.3

**Comment by moishinetzer** [comment]
Wow... Now that is fast support! It looks beautiful

I had noticed you only added this for dracula and not dracula colorful, would you be able to add it for that schema as well?

Thanks for the INCREDIBLY fast update

**Comment by WhiteVermouth** [comment]
`Dracula Colorful` is also supported. If you find this feature missing, **Restore Default** the `Dracula Colorful` scheme, and restart IDE.

**Comment by moishinetzer** [comment]
Sorry can you expand on where I can find **Restore Default** ?

**Comment by moishinetzer** [comment]
Thank you very much again - Keep up the great work!
