### ISSUE TITLE
Theme loaded with wrong color scheme

### ISSUE THREAD

**Issue by FelipeRosa** [dracula/jetbrains#4]
After setting the theme in `Appearance & Behavior > Appearance` to Dracula, all the UI colors are set correctly. The problem is that when I restart GoLand the tree view component's background color is incorrectly set.

![image](https://user-images.githubusercontent.com/2042166/61964990-93769e80-afa5-11e9-8eb8-005eff553b70.png)

Also the editor colors are all wrong.

![image](https://user-images.githubusercontent.com/2042166/61965252-27486a80-afa6-11e9-802b-0958712d941b.png)
 
I'm running on macOS Mojave (10.14.5), GoLand 2019.2 and Dracula Theme 1.4.0.

**Comment by WhiteVermouth** [comment]
1. Tree View Component bug can't be reproduced on my mac, perhaps it's a bug of GoLand.
2. Support for Go Language Color Scheme will be added in next version (1.4.1).

**Comment by WhiteVermouth** [comment]
New version v1.4.1 has been submitted. Once it is approved by JetBrains, check it out.

**Comment by FelipeRosa** [comment]
Ok :)

I'll try to figure out the Tree view thing. 

Thanks
