### ISSUE TITLE
contrast issue with resolving git merge conflicts

### ISSUE THREAD

**Issue by benatshippabo** [dracula/jetbrains#44]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

The arrows are hard to read:
![image](https://user-images.githubusercontent.com/66273043/106681225-f1118100-6574-11eb-89fd-939b7df6516a.png)

![image](https://user-images.githubusercontent.com/66273043/106681281-0c7c8c00-6575-11eb-9ccd-23eaa873e797.png)

**Comment by WhiteVermouth** [comment]
Upgrade to v1.11.0

**Comment by benatshippabo** [comment]
Hmm on the non-colorful theme I'm still seeing the same background colors even after reinstalling and updating.

**Comment by WhiteVermouth** [comment]
Go to **Preferences/Settings -> Editor -> Color Scheme**
![image](https://user-images.githubusercontent.com/13076049/107106853-b192af80-6868-11eb-8a0a-ab05a6a582b2.png)
Click the gear button, if you ever edited the color scheme, the **Restore Defaults** option should be enabled, click **Restore Defaults**, then apply.

**Comment by benatshippabo** [comment]
Whew that was it. Thanks again
