### ISSUE TITLE
"Matched brace" is not distinguishable

### ISSUE THREAD

**Issue by tsdh** [dracula/jetbrains#46]
I'm using the theme version 1.11.0 in the Dracula Colorful variant.  I like it very much.  The only thing which I've had to tweak manually was the background color for "Matched brace" because it is almost impossible to distinguish it especially on the current, highlighted line.  Here's a screenshot showing it's default appearance.

![image](https://user-images.githubusercontent.com/103854/107472679-a9d85100-6b6f-11eb-9758-c041466cd84b.png)

It's hard to see that the cursor is on the closing paren of the ­­­containsKey call.  The slight greenish background doesn't stand out.

This is the relevant setting:

![image](https://user-images.githubusercontent.com/103854/107472793-e1df9400-6b6f-11eb-85b2-59ca8f4360aa.png)

I'd suggest to make the "Matching brace" style a bit more outstanding given that this style has a very high usability value when editing in nested, parenthesized expressions.

**Comment by WhiteVermouth** [comment]
Thank you for your feedback. This issue will be fixed in next version.

**Comment by WhiteVermouth** [comment]
Upgrade to v1.11.1

**Comment by tsdh** [comment]
Thanks, works!
