### ISSUE TITLE
Styling of IDEA popups

### ISSUE THREAD

**Issue by andriesfc** [dracula/jetbrains#47]
It is possible to style the help windows as well. It really sticks out like sore thumb:

![image](https://user-images.githubusercontent.com/69518948/107924596-e2b36400-6f7b-11eb-83e2-649e7de7afc6.png)

**Comment by WhiteVermouth** [comment]
1. How did you popup this help window? (keyboard shortcut or other ways)
2. Take a screenshot of `Preferences/Settings -> Editor -> Color Scheme`, like this:

![image](https://user-images.githubusercontent.com/13076049/107962776-5425fd80-6fe2-11eb-9257-f4f237f712a7.png)

3. If the `Restore Defaults` option is enabled, click it and then apply.

**Comment by andriesfc** [comment]
Just press `CONTROL+Q` on any element which has help associated with it. My keyboard scheme is windows 10. I do not have any special customizations of the base Dracula scheme.

**Comment by WhiteVermouth** [comment]
![image](https://user-images.githubusercontent.com/13076049/108068899-ac6e0580-709d-11eb-81dc-3fb0d4ce6055.png)

This bug was fixed in previous release. See issue #38.
Make sure you've installed the latest version and no customization is applied.
