### ISSUE TITLE
Pycharm TODO highlight changes not working

### ISSUE THREAD

**Issue by trumantnt** [dracula/jetbrains#48]
Since Python comment symbol is # instead of // , the intended highlight color does not appear in Pycharm.

Also any change made in Settings -> Editor -> Color Scheme -> General -> TODO defaults would not translate as well.

**Comment by WhiteVermouth** [comment]
I just can't reproduce. I used PyCharm 2020.3 and Dracula Theme v1.11.1
![image](https://user-images.githubusercontent.com/13076049/109099468-21a49f00-775e-11eb-84f7-43dd1742456e.png)

**Comment by trumantnt** [comment]
I figured it out. It's not because of Dracula Theme, but because of settings from older version. It's a sneaky issue across different IDEs of Jetbrain.

I made a complete wipe of PyCharm and all programs related to Jetbrain, used Listary to find old setting files and delete them. And problem is solved.
