### ISSUE TITLE
Problem Datagrip version build March 31, 2021

### ISSUE THREAD

**Issue by cesguto** [dracula/jetbrains#49]
Hello.
After updating the datagrip 2021 .1 to a version built on March 31, 2021 the Dracula theme was removed and even trying to reinstall it is still not shown.
Can you help me?
![image](https://user-images.githubusercontent.com/11931250/113429295-aa8ea600-93ae-11eb-8a51-3131b3a42fdc.png)

**Comment by jorgealfonsogarcia** [comment]
Hello @cesguto .
I'm currently have the same problem with the Dracula theme for IntelliJ.
How did you solve it?
Thanks!

**Comment by cesguto** [comment]
> Hello @cesguto .
> I'm currently have the same problem with the Dracula theme for IntelliJ.
> How did you solve it?
> Thanks!

Hi,

I applied the latest version update and it worked again
![image](https://user-images.githubusercontent.com/11931250/117364563-72d6ba80-ae94-11eb-8c5b-b2c22dc06df4.png)
