### ISSUE TITLE
Improve text selection

### ISSUE THREAD

**Issue by AndSDev** [dracula/jetbrains#5]
Remove "Selection foreground" setting:
https://github.com/WhiteVermouth/jetbrains-dracula/blob/069e987288e273b13b36f61f4556fdd2abb4e5ad/src/main/resources/themes/Dracula.xml#L12
Result:
![image](https://user-images.githubusercontent.com/13585370/63926142-01eec680-ca54-11e9-956c-cf17b0d7336e.png)

**Comment by WhiteVermouth** [comment]
Thanks. Code committed and will be released to JetBrains Plugin Repository in next version.
