### ISSUE TITLE
Bad contrast in 2021.1 Github PR commits tab

### ISSUE THREAD

**Issue by benatshippabo** [dracula/jetbrains#50]
In the pull requests tab, under commits:
![image](https://user-images.githubusercontent.com/66273043/114752166-dbee6680-9d0a-11eb-80c8-80c4c0dea64d.png)

the (non-linear commit history) warning message is a very difficult to read:
![image](https://user-images.githubusercontent.com/66273043/114752128-d2fd9500-9d0a-11eb-9efd-8fc2c4a6af78.png)

**Comment by WhiteVermouth** [comment]
Fixed in v1.11.4

**Comment by benatshippabo** [comment]
Thanks @WhiteVermouth 🥇
