### ISSUE TITLE
Incompatible: requires IDE build 211.* or older on IntelliJ 2021.2 EAP

### ISSUE THREAD

**Issue by NGRichter** [dracula/jetbrains#51]
![Dracula_IntelliJ](https://user-images.githubusercontent.com/22129925/120161052-32e6c700-c1f7-11eb-994b-b99fe050c9f8.png)

About page:

IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.3116.43, built on May 27, 2021

Runtime version: 11.0.11+9-b1460.1 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2040M
Cores: 12

Kotlin: 212-1.4.32-release-IJ3116.43

**Comment by WhiteVermouth** [comment]
Please upgrade to v1.11.5. But because the 2021.2 is an EAP version now, `Dracula Theme` may not behave as expected sometimes.
