### ISSUE TITLE
Wrong contrast in commit diff & highilighted selection in pycharm (Dracula Pro theme)

### ISSUE THREAD

**Issue by inrumi** [dracula/jetbrains#52]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Current commit diff looks like this for yaml changes:
![image](https://user-images.githubusercontent.com/18445985/123817448-c9251000-d8bd-11eb-944f-aac9e78d8f59.png)

I looked through other themes and looks like every other theme have a more muted color
![image](https://user-images.githubusercontent.com/18445985/123817772-0e494200-d8be-11eb-9906-fae75e147e82.png)

also there's minimal difference between backgrounds in selected text that is already highlighted:
![image](https://user-images.githubusercontent.com/18445985/123820858-857fd580-d8c0-11eb-962a-3b9eb9447986.png)

Example darcula theme:
![image](https://user-images.githubusercontent.com/18445985/123824052-51f27a80-d8c3-11eb-98db-d5e7b9e69f39.png)

**Comment by WhiteVermouth** [comment]
@zenorocha Here's a Dracula Pro issue.
