### ISSUE TITLE
Dracula Pro theme not compatible with 2021.2

### ISSUE THREAD

**Issue by AndreasNasman** [dracula/jetbrains#53]
Hi!

Dracula Pro version 1.3.1 is incompatible with the newest version of Intellij, i.e. version 2021.2 (IU-212.4746.92).

![Screen Shot 2021-07-28 at 13 47 16](https://user-images.githubusercontent.com/17124245/127311343-a7cdeb39-3f4b-43d4-8563-c384fbaf2813.png)

I suppose an update is in progress with the required changes? 🙂

– Andreas

**Comment by WhiteVermouth** [comment]
Probably email @zenorocha or feedback on Gumroad.

**Comment by zenorocha** [comment]
You can download the latest version from gumroad.com which contains a fix for that.

Thanks @AndreasNasman!

**Comment by AndreasNasman** [comment]
Thanks for the update! 🙂
