### ISSUE TITLE
Background Color Git History

### ISSUE THREAD

**Issue by SupianIDz** [dracula/jetbrains#56]
Thank you for creating the coolest theme.

I think the background color in git history on PHP Storm should be the same as Dracula's base color, not like this.

![wwww](https://user-images.githubusercontent.com/37969970/129218586-558e22f4-a3b9-42a1-8564-fb84e9f76fed.png)

**Comment by WhiteVermouth** [comment]
I can't reproduce your problem. Further details needed.

![image](https://user-images.githubusercontent.com/13076049/129378107-8b0e18c1-44a0-4316-a0fc-921baa7db7d9.png)
