### ISSUE TITLE
Color of mnemonic bookmark support

### ISSUE THREAD

**Issue by optionals** [dracula/jetbrains#57]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
<img width="371" alt="截屏2021-08-13 上午10 11 39" src="https://user-images.githubusercontent.com/7846036/129295263-088967ee-d145-41a2-b351-07f7ea104e50.png">

theme attribute keys:
 https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/themes/metadata/IntelliJPlatform.themeMetadata.json

Platform UI Guidelines: 
https://jetbrains.design/intellij/principles/platform_theme_colors/#ui-components.

**Comment by WhiteVermouth** [comment]
This feature is implemented in v1.12.4. Here is some previews:

Add Mnemonic Bookmark:
![image](https://user-images.githubusercontent.com/13076049/148414172-72dd2fea-c1aa-4f47-afd1-94e356e1d492.png)

Bookmark Tab:
![image](https://user-images.githubusercontent.com/13076049/148414239-9be7a8b5-b1e3-4f42-8ad5-0829055e781c.png)

Check it out. And feedback is welcome.

**Comment by optionals** [comment]
> This feature is implemented in v1.12.4. Here is some previews:
> 
> Add Mnemonic Bookmark: ![image](https://user-images.githubusercontent.com/13076049/148414172-72dd2fea-c1aa-4f47-afd1-94e356e1d492.png)
> 
> Bookmark Tab: ![image](https://user-images.githubusercontent.com/13076049/148414239-9be7a8b5-b1e3-4f42-8ad5-0829055e781c.png)
> 
> Check it out. And feedback is welcome.

solved, thx.
