### ISSUE TITLE
Indent guide and Visual guides are too bright

### ISSUE THREAD

**Issue by MatyCZ** [dracula/jetbrains#59]
Indent guide and Visual guides are too bright and are disruptive. In VS Code they are less disruptive.

![indentGuide](https://user-images.githubusercontent.com/318575/131635876-3523d558-d289-47da-b99d-3bb9454fa1b3.png)

**PhpStorm**
![indentGuidePhpStorm](https://user-images.githubusercontent.com/318575/131635293-1e688436-87d0-40b8-aa8b-561d7bb7656c.png)

**VS Code**
![indentGuideVSCode](https://user-images.githubusercontent.com/318575/131635316-41c52272-bb71-4420-b5e7-aa11f33dbf62.png)

**Comment by WhiteVermouth** [comment]
Upgrade to v1.13.2
