### ISSUE TITLE
Not working in Ubuntu but its working in my macOS

### ISSUE THREAD

**Issue by hellosagar** [dracula/jetbrains#61]
This is a screenshot of the plugin installed

![Screenshot from 2021-09-01 18-26-40](https://user-images.githubusercontent.com/50016799/131675154-b0d6847a-3cd4-46fe-95b0-671f6b3f5226.png)

and it's not showing any Dracula option in Appearance

**Comment by WhiteVermouth** [comment]
Sorry for the slow response. Is this bug still exists at this time? I didn't test the plugin on Ubuntu OS before releasing.

**Comment by hellosagar** [comment]
Don't know now because now I moved to mac, if possible I will check and try

**Comment by ramsaysewell** [comment]
I've been able to test the latest raise of the plugin in Ubuntu and find it to work as expected. I'll go ahead and close this issue. 

Feel free to reopen if you come across it again.
