### ISSUE TITLE
Plugin error: Plugin 'Dracula Theme' (version '1.12.1') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is WS-213.3714.441

### ISSUE THREAD

**Issue by Litten1106** [dracula/jetbrains#63]
Plugin error: Plugin 'Dracula Theme' (version '1.12.1') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is WS-213.3714.441
i update to webstorm 2021.3 eap，now i have to use another theme instead of , but i'd like to use dracula theme

**Comment by WhiteVermouth** [comment]
Upgrade to v1.12.2

**Comment by Litten1106** [comment]
> Upgrade to v1.12.2

awesome, i got the lastest version
