### ISSUE TITLE
Jetbrains Theme does not work at all

### ISSUE THREAD

**Issue by seriouz** [dracula/jetbrains#64]
I've installed the latest version of Rider and applied the latest version auf the Dracula theme. Nothing changes.
Is the theme broken? (The Material theme works flawlessly.)

Edit: I would by pro. If i knew that the theme is working 😞

**Comment by WhiteVermouth** [comment]
What's your OS and Rider version?

**Comment by seriouz** [comment]
OS is Win10

Rider 2021.3 EAP 8:
![grafik](https://user-images.githubusercontent.com/4722613/143285472-320862e3-8d3a-4baf-84fa-1d119d24520e.png)

Rider 2021.2.2:
![grafik](https://user-images.githubusercontent.com/4722613/143285969-090761fe-5c4a-4280-b615-03d93d2b1036.png)

**Comment by WhiteVermouth** [comment]
Look like you didn't apply `Dracula Theme`.
![image](https://user-images.githubusercontent.com/13076049/143602967-f4fa0b6f-d41f-4d3d-85bc-6524315c125f.png)

**Comment by seriouz** [comment]
How did you install the theme?

**Comment by WhiteVermouth** [comment]
Directly install from Plugin Marketplace.
![image](https://user-images.githubusercontent.com/13076049/143603579-f13fd003-c6ae-44ef-a844-8365fcfb190d.png)

**Comment by seriouz** [comment]
omega lul... i uninstalled the Dracula Theme plugin, reinstalled the plugin and now its working!
Thanks @WhiteVermouth for the indirect hint :)
