### ISSUE TITLE
Bookmark-Icon not visible in PHPStorm-Project-Tree

### ISSUE THREAD

**Issue by ZYZ64738** [dracula/jetbrains#66]
Howto Reproduce:
1) 
![image](https://user-images.githubusercontent.com/9817678/145552308-404baf96-bb62-4ff9-84ba-714c049c08ff.png)
2) mark a folder as bookmarked (select folder in project-Tree and hit F11)
3) if the folder is not selected/highlightet you cannot see the icon - but a certain "marging" to the left.

> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
![image](https://user-images.githubusercontent.com/9817678/145552062-d1f5258a-1c4b-4d97-a2dd-076cf2f2fc64.png)

**Comment by WhiteVermouth** [comment]
Upgrade to v1.12.3

**Comment by ZYZ64738** [comment]
Thx ... works for me:

![image](https://user-images.githubusercontent.com/9817678/147647489-0ebf7a07-8795-435b-98ea-c166dc7c0c21.png)
