### ISSUE TITLE
Bad contrast for selected item in JetBrains IntelliJ IDEA content assist dialog

### ISSUE THREAD

**Issue by knutwannheden** [dracula/jetbrains#67]
I am using Dracula Pro in Jetbrains IntelliJ IDEA for Java and I have a hard time reading the Java package names shown in dialogs like the content assist dialog for the currently selected line. See second row in pupup in screenshot (to the right of  `Tracer` it reads `io.opentelemetry.api.trace` but at least to me that is nearly invisible).

<img width="292" alt="image" src="https://user-images.githubusercontent.com/408765/145784354-051eb2d4-d5d5-41a4-9a63-f2682d890451.png">

I wouldn't mind manually changing either the color highlighting the current row or the color of the font for the package name, but I don't know which causes more problems and I also couldn't figure out what I have to change in the settings.

**Comment by WhiteVermouth** [comment]
Sorry, we can't provide any help on `Dracula PRO` here. You may send your feedback to @zenorocha.

**Comment by knutwannheden** [comment]
Sorry, I didn't realize I reported this issue against the wrong repo. Sorry about that!

**Comment by knutwannheden** [comment]
@zenorocha: Can you provide a link where feedback / issues like this one can be reported? I couldn't find anything on your website.
