### ISSUE TITLE
Theme claims to be incompatible with the current IntelliJ EAP 2022.1

### ISSUE THREAD

**Issue by tsdh** [dracula/jetbrains#70]
I'm always using the current EAP version of IntelliJ and every now and then the theme is marked as incompatible like now:
![image](https://user-images.githubusercontent.com/103854/152293640-dd6cf4b2-77d5-48ac-adb5-2497a22ae168.png)

My version of the theme is 1.12.4, IntelliJ reports as:
```
IntelliJ IDEA 2022.1 EAP (Ultimate Edition)
Build #IU-221.3427.89, built on January 26, 2022
```
I'm pretty sure this is not an actual incompatibility in that the theme would need restructuring for the current IntelliJ version but just a version descriptor needed to be tweaked. 

Is this intentional that you are so restrictive with versions, i.e., you want to allow only versions which have proven to be compatible with the theme?  Other themes seem to be much more relaxed with respect to that, e.g., the monokai pro theme (https://github.com/subtheme-dev/monokai-pro) has had its last update in November 2021 (long before the 2022.1 EAP) but isn't marked as incompatible in the plugin market place (same for One Dark Theme, Gradianto, Dark Purple Theme, Solarized Theme, ...).

**Comment by mozesa** [comment]
Same here!
But I found a workaround:
* disable it
* restart the IDE
* enable it and enjoy it as long as you don't restart the IDE

![image](https://user-images.githubusercontent.com/49973426/152302556-9859252f-bfb3-4e88-998c-93c26c790688.png)

**Comment by WhiteVermouth** [comment]
Upgrade to v1.13.0

**Comment by WhiteVermouth** [comment]
And yes, it's intentional that I restrict the IntelliJ versions the theme would be compatible with. Because breaking changes from JetBrains may crash the plugin.

**Comment by tsdh** [comment]
@WhiteVermouth Would crashing the plugin result in anything different from a user's POV?  I guess it would not crash the complete IDE.  And do incompatibilities resulting in crashes occur really that often?

I for one could live with some crashes on upgrading to a new EAP version.  I mean, there are plenty of IntelliJ components which sometimes crash and you get an "IDE error occurred" notification.  Having one notification more wouldn't be the straw that breaks the camel's back.

IMHO, the inconvenience of using a theme one is not used to is bigger than a crash notification every few month.  I mean, the coloring of a theme conveys semantic meaning, i.e., it allows to distinguish fields from locals, etc.  So if my beloved Dracula theme doesn't load although it technically could, that's annoying.

Anyway, that's obviously up to you to decide.  I'm fine with any decision but will file a new "version bump" bug more promptly in the future. ;-)

**Comment by WhiteVermouth** [comment]
@tsdh Thanks for your advice. Check out `v1.13.1`. Now only the **minimum** IntelliJ version is required, in `v1.13.1` it is 2021.1, and as expected it will always be compatible with the future IntelliJ IDE by default even if it is not released now.

**Comment by tsdh** [comment]
Thank you, and thanks a lot for this great theme!
