### ISSUE TITLE
Occurrences not highlighted in right gutter

### ISSUE THREAD

**Issue by schophil** [dracula/jetbrains#72]
Highlighted occurrences are not visible in right gutter.

Example in light theme:

<img width="850" alt="Screenshot 2022-05-12 at 09 08 46" src="https://user-images.githubusercontent.com/11485058/168012455-1f8aed5e-a387-4daa-8ca3-b8d26f619f81.png">

Same in Dracula theme:

<img width="850" alt="Screenshot 2022-05-12 at 09 09 16" src="https://user-images.githubusercontent.com/11485058/168012481-f2bbe21e-34e9-4af9-9ab7-9102d045ce2c.png">

**Comment by WhiteVermouth** [comment]
Upgrade to v1.13.2
