### ISSUE TITLE
Any updates coming for Dracula Pro?

### ISSUE THREAD

**Issue by mrweiner** [dracula/jetbrains#74]
Dracula PRO has been broken on the past few phpstorm releases, and the last Pro release was back in April. Any plans to release any compatibility updates? I know this doesn't exactly pertain to this repo, but not sure of the best place to ask about this.

**Comment by ramsaysewell** [comment]
Hey @mrweiner,

Dracula PRO's new update is soon approaching and you can stay up to date with all the latest improvements and announcements on our [Discord server](https://discord.com/invite/yDcFsrYuq9).
