### ISSUE TITLE
Navigation bar issues after update to PhpStorm 2022.3

### ISSUE THREAD

**Issue by mostafa-rz** [dracula/jetbrains#77]
Hi, I updated my phpstorm to version 2022.3, Build #PS-223.7571.212, built on December 1, 2022. The navigation bar now has some problems. It expands and collapses automatically when the path is long.

![Screenshot 2022-12-16 130010](https://user-images.githubusercontent.com/71334549/208094222-e08aba66-d24d-45d4-93e9-d69cdf2bad8a.png)

When the path is short it is working great. 

![Screenshot 2022-12-16 130518](https://user-images.githubusercontent.com/71334549/208094519-e5935a41-530a-4560-a09a-83496a4415cc.png)

**Comment by WhiteVermouth** [comment]
Looks like a bug in IDE itself, does this issue still exist?

**Comment by mostafa-rz** [comment]
I update it to the new version with the new UI and it is resolved now.
