### ISSUE TITLE
Python Packages in white mode

### ISSUE THREAD

**Issue by mateusadada** [dracula/jetbrains#78]
Hello,

I'm using Dracula Theme and I noticed that in the Python Packages option it's not dark like it should be. I performed some tests and observed that when I switch to the default black version it works. Below are two images to demonstrate:

**Theme Dark activated:**

![Theme Dark](https://user-images.githubusercontent.com/125929822/230774371-e9b3d645-60fb-4576-8c9f-be2b5b05af36.png)

----------------------

**Theme Dracula activated:**

![Theme Dracula](https://user-images.githubusercontent.com/125929822/230774389-9e57e613-c33e-4a20-9f5d-3fef2cd6167c.png)

----------------------

Current version: *PyCharm 2023.1 PC-231.8109.197 March 29, 2023*
Python version: *3.11.3 (64-bit)*
Plugin Dracula Theme version: *1.14.2*

Sorry about anything, it was my first Issue. Thank you.

**Comment by WhiteVermouth** [comment]
It seems that this is a bug in the JetBrains IDE itself, and unfortunately, I haven't come across any solution to resolve this issue. Some other 3rd-party themes are also affected by this bug.
