### ISSUE TITLE
Installation instructions are impossible to follow

### ISSUE THREAD

**Issue by Drarok** [dracula/jetbrains#8]
The [installation instructions][1] tell you to copy the `Dracula.icls` file to install, but no such file exists in the repository.

[1]: https://draculatheme.com/jetbrains/

**Comment by Drarok** [comment]
Ah. I started by looking in my IDE but the plugin isn't listed – I think because I'm running an old version. Thanks for updating the README!

**Comment by Kyvrel** [comment]
the number line' color also changed, is it intended?
I remember it does not changed before
![深度截图_选择区域_20191114101505](https://user-images.githubusercontent.com/25075484/68820919-bd281280-06c7-11ea-9e76-5875802f4018.png)

**Comment by WhiteVermouth** [comment]
@qiaocci It's intended.
