### ISSUE TITLE
Color of default button in Dracula Pro

### ISSUE THREAD

**Issue by knutwannheden** [dracula/jetbrains#80]
The Dracula Pro themes have the same color for default and non-default buttons. I hadn't actually noticed this, which is why I reported an IDEA issue, because I was under the impression that IDEA did the wrong thing when I pressed the Enter key: https://youtrack.jetbrains.com/issue/IDEA-320316

This is what it looks like with the Dracula theme (non pro), where the default button has a different color:
<img width="435" alt="image" src="https://github.com/dracula/jetbrains/assets/408765/e3e21c38-2296-4a5e-93ab-0f5167e55721">

With the Dracula Pro theme I cannot see any difference between the default and the non-default buttons:
<img width="435" alt="image" src="https://github.com/dracula/jetbrains/assets/408765/5b3bd189-0171-4485-a262-bda8088ce512">

**Comment by WhiteVermouth** [comment]
Sorry, this repository is dedicated to resolving issues related to the Open Source version. If you have any problem on the Pro version, we suggest you to reach out to the author directly through Gumroad.

**Comment by knutwannheden** [comment]
OK. Sorry about that.
