### ISSUE TITLE
Idea Annotate

### ISSUE THREAD

**Issue by fenglangjunzi** [dracula/jetbrains#84]
<img width="867" alt="image" src="https://github.com/dracula/jetbrains/assets/5000975/535b8bd6-90f8-429b-a7c9-5493265e229b">

**Comment by WhiteVermouth** [comment]
Can't reproduce here, does this BUG persist after restarting the IDE?

**Comment by fenglangjunzi** [comment]
Restarting has no effect, and I also tried to reinstall the plug-in, but it still didn't work.

**Comment by fenglangjunzi** [comment]
https://github.com/dracula/jetbrains/assets/5000975/6befd7c5-86c2-4ff5-8ea1-8b2f05ba7378

**Comment by fenglangjunzi** [comment]
The same file is normally displayed on git, but there is a problem with svn.

**Comment by WhiteVermouth** [comment]
Thanks for your feedback, I've never tested on SVN, I'll try to reproduce again with SVN.

**Comment by WhiteVermouth** [comment]
I have no idea why this exception happens. But I really reproduce it successfully, it looks like a bug inside IntelliJ IDE, but not the theme plugin. Normally, there should be a background color around the Git Blame Author, but it may lost under some circumstances.

**Comment by WhiteVermouth** [comment]
Upgrade to v1.15.1, now even the background color is lost, the Git Blame remains clear.
