### ISSUE TITLE
Dracula Colorful not works in v1.15.0

### ISSUE THREAD

**Issue by chenyanchen** [dracula/jetbrains#85]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

![image](https://github.com/dracula/jetbrains/assets/23415847/9e07416d-0411-413d-8752-dd6f7226cb76)

**Comment by WhiteVermouth** [comment]
To workaround the bug in the latest IDE, follow these steps:
	1.	Open the IDE.
	2.	Go to the "Settings" menu.
	3.	Navigate to "Editor" and select "Color Scheme."
	4.	On the right panel, choose "Dracula Colorful" as the color scheme.
	5.	Click "OK" to apply the changes.
This should resolve the issue with the color scheme in the IDE.

<img width="1012" alt="image" src="https://github.com/dracula/jetbrains/assets/13076049/2f63d072-6e76-4e7b-b625-46c2d0e3c3b1">

**Comment by chenyanchen** [comment]
> To workaround the bug in the latest IDE, follow these steps: 1. Open the IDE. 2. Go to the "Settings" menu. 3. Navigate to "Editor" and select "Color Scheme." 4. On the right panel, choose "Dracula Colorful" as the color scheme. 5. Click "OK" to apply the changes. This should resolve the issue with the color scheme in the IDE.
> 
> <img alt="image" width="1012" src="https://user-images.githubusercontent.com/13076049/257110798-2f63d072-6e76-4e7b-b625-46c2d0e3c3b1.png">

That's works, thanks.

**Comment by CidTori** [comment]
Well the background is not white but it’s not colorful anymore ☹

**Comment by MaurycyWojda** [comment]
This had no effect for me. I used Dracula Colorful by default, and now both themes have a white background.
