### ISSUE TITLE
After updating 1.15.0, background color is white

### ISSUE THREAD

**Issue by jintak0401** [dracula/jetbrains#86]
I update it to 1.15.0 and background color of code area becomes white at Dracula Colorful. However, it looks nice at Dracula.

Environment

PyCharm 2023.2
Windows
Dracula theme 1.15.0

### Dracula Colorful

![image](https://github.com/dracula/jetbrains/assets/32933980/6cf8ac42-2a3f-4243-bf0d-cecf3ef3023e)

### Dracula

![image](https://github.com/dracula/jetbrains/assets/32933980/6846ed25-84cb-4916-8622-9ecfbb12029a)

**Comment by WhiteVermouth** [comment]
Duplicated with #85 

Solution: https://github.com/dracula/jetbrains/issues/85#issuecomment-1657477338

**Comment by CidTori** [comment]
Well with the workaround the background is not white but it’s not colorful anymore ☹

**Comment by Scryper** [comment]
The solution mentioned in #85 does not work for me (neither for @MaurycyWojda see last comment on 85). I have the white background on both Dracula and Dracula Colorful. There is also the same issue in the "Terminal" pane.

I am using WebStorm 2023.2

**Comment by moeshin** [comment]
`Settings` > `Editor` > `Color Scheme`, select `Dracula Colorful`, may need to restart.

After updated, it changed to `Classic Light`.

**Comment by RhysLees** [comment]
> `Settings` > `Editor` > `Color Scheme`, select `Dracula Colorful`, may need to restart.
> 
> After updated, it changed to `Classic Light`.

This worked for me, thanks

**Comment by mkomko** [comment]
Why does this happen? Is the bug in IntelliJ or the theme? I get confused every time.

**Comment by WhiteVermouth** [comment]
> Why does this happen? Is the bug in IntelliJ or the theme? I get confused every time.

It's a bug in IntelliJ, the IDE does the unload and load job every time the plugin get updated, but sometimes it doesn't work well.

**Comment by mkomko** [comment]
> > Why does this happen? Is the bug in IntelliJ or the theme? I get confused every time.
> 
> It's a bug in IntelliJ, the IDE does the unload and load job every time the plugin get updated, but sometimes it doesn't work well.

But isn't it strange that even switching to the theme manually doesn't fix the setting? Did you open an issue on YouTrack?

**Comment by WhiteVermouth** [comment]
@mkomko Could you provide a screen recording? I'm unable to reproduce the issue locally. It seems to function properly for some users while others are reporting issues, which is rather confusing.

**Comment by mkomko** [comment]
@WhiteVermouth Here you go. BTW, I just noticed that for me it only happens with the "Colorful" theme. Have you tried reproducing it with that?

And: Thank you very much for your awesome theme! So beautiful 😃 

https://github.com/dracula/jetbrains/assets/8350714/f11c07e0-98ea-482f-a067-a6437b45c329

**Comment by WhiteVermouth** [comment]
<img width="806" alt="image" src="https://github.com/dracula/jetbrains/assets/13076049/0080265c-11d1-4813-89f5-ee790cdf7abd">

@mkomko At this setting section, manually change the color scheme from `Classic Light` to `Dracula Colorful` then apply it. Let me explain: the theme is composed with two parts: UI and editor color scheme. Normally, the IDE should switch both the UI and editor color scheme, but currently it loses the editor part very frequently, and as you see, the editor is white(Which is exactly the default `Classic Light` color scheme).

**Comment by mkomko** [comment]
@WhiteVermouth Yes I know that fixes it, but it's only a workaround. The next update will change it back and I'll have to look it up all over again 😉

**Comment by Litten1106** [comment]
> > `Settings` > `Editor` > `Color Scheme`, select `Dracula Colorful`, may need to restart.
> > After updated, it changed to `Classic Light`.
> 
> This worked for me, thanks

i think this hacker way also get problem while u toggle between 2 tabs, u will also see a white bg about 1 second

**Comment by dhennerperes** [comment]
same problem

**Comment by lukens** [comment]
I have the same issue after updating Dracula theme.

I've tried changing theme, restarting, changing theme again, over and over.

The background changes when I switch to any other theme, but with Dracula or Dracula Colourful, it always switched back to white.

I don't seem to have "Classic Light" as an option, but have tried "IntelliJ Light".

**Comment by lukens** [comment]
It seems 1.15.0 works with Dracula Colourful, but 1.15.1 is broken in both variants

**Comment by WhiteVermouth** [comment]
Try v1.15.2

In version 1.15.2 of the plugin, a new patch has been added. When you switch the theme to either "Dracula" or "Dracula Colorful" from any other theme, the plugin will automatically adjust the editor color scheme to match the selected theme. This ensures a seamless transition and a consistent look for the user.

Attention: you may restart you IDE after upgrading to the new release.

**Comment by lukens** [comment]
Looks like it's working now. I had real issues updating it, but that seemed to be an IntelliJ issue, as it was the same for other plugins. Kept hanging at "Unloading plugin ...".

I found closing all open projects seemed to enable it to then work.

**Comment by mkomko** [comment]
> Try v1.15.2

Worked for me, thank you very much!
