### ISSUE TITLE
only code editor is using dracula

### ISSUE THREAD

**Issue by samuelcolvin** [dracula/jetbrains#89]
Thanks so much for this plugin, it's generally great and I use it all the time.

As of the most recent release, only the code editor seems to have dracula colors, the rest of the UI seems to be using default dark mode.

The only thing changed was that I updated the dracula plugin, I don't know what version I was using before.

![image](https://github.com/dracula/jetbrains/assets/4039449/37963f7f-2637-4bbb-ad46-094428155ca2)

### Versions

Dracula: 1.15.2

pycharm:

```
PyCharm 2023.2.1 (Professional Edition)
Build #PY-232.9559.58, built on August 22, 2023
Licensed to Samuel Colvin
You have a perpetual fallback license for this version.
Subscription is active until September 23, 2024.
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-33-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4004M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    org.rust.lang (0.4.201.5424-232)
    com.vermouthx.idea (1.15.2)
    com.github.copilot (1.2.22.3129)
    com.intellij.lang.liquid (232.8660.88)
    name.kropp.intellij.makefile (232.8660.88)
    ru.meanmail.plugin.requirements (2022.4.1)
    ru.adelf.idea.dotenv (2023.2)
    com.koxudaxi.pydantic (0.4.8)
    mobi.hsz.idea.gitignore (4.5.1)

Current Desktop: ubuntu:GNOME
```

**Comment by WhiteVermouth** [comment]
Hi,

Have you tried restart IDE and set appearance theme to Dracula or Dracula Colorful.

PS: To setup appearance theme, go to Settings -> Appearance & Behavior -> Appearance

[image.png]

- Zihan Ma

------- Original Message -------

**Comment by samuelcolvin** [comment]
awesome that works, sorry for the noise.

Is there a way to sponsor this plugin? I don't see github sponsorship enabled.

**Comment by WhiteVermouth** [comment]
Hi @samuelcolvin 

If you want to sponsor this plugin, there is a donation link on the JetBrains MarketPlace page: [https://plugins.jetbrains.com/plugin/12275-dracula-theme](https://plugins.jetbrains.com/plugin/12275-dracula-theme)

It's the same to this [Buy Me a Coffee](https://www.buymeacoffee.com/nszihan) link.

<img width="1392" alt="User Interface Editor" src="https://github.com/dracula/jetbrains/assets/13076049/e51afc0e-b659-44df-ae88-b36e524c3348">

Thank you.
