### ISSUE TITLE
Active Tab colour is indistinguishable from inactive tabs 

### ISSUE THREAD

**Issue by CoolTomatos** [dracula/jetbrains#9]
![image](https://user-images.githubusercontent.com/24667806/67678431-df5f2800-f986-11e9-9d45-18428a8e2e53.png)
As in the screenshot, it's hard to tell which is the active tab. 
Also that Main class is always shown in active colour, I don't know if that's wanted.

**Comment by WhiteVermouth** [comment]
The underline will be regressed in next release to avoid such situation.

**Comment by CoolTomatos** [comment]
Fixed in 22008083201866c6ee3df0558e868b3dbb8cdb6a.
