### ISSUE TITLE
Dracula Colorful not working in IntelliJ 2024.2?

### ISSUE THREAD

**Issue by jiacheng-0** [dracula/jetbrains#93]
I am not able to find this on Marketplace, anyone else have this issue?

**Comment by WhiteVermouth** [comment]
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/ece3a7bd-54da-4f6d-83cf-1a85f7c5cf02">

Can't reproduce. Try to install directly from https://plugins.jetbrains.com/plugin/12275-dracula-theme
